const endpoints = {
    SERVER_SEND_NOTIFICATION: 'SERVER_SEND_NOTIFICATION',
    CLIENT_REQUEST_SAVE_SCHEMA: 'CLIENT_REQUEST_SAVE_SCHEMA',
    SERVER_RESPONSE_SAVE_SCHEMA: 'SERVER_RESPONSE_SAVE_SCHEMA',
    CLIENT_REQUEST_GENERATE_CODE: 'CLIENT_REQUEST_GENERATE_CODE',
    SERVER_RESPONSE_GENERATE_CODE: 'SERVER_RESPONSE_GENERATE_CODE',
};

export default endpoints;